using System.Collections.Generic;

namespace Extensions.Colors
{

	public partial class HSVColor
	{

		/// <summary>
		/// Lista com todas as <see cref="HSVColor"/> com nomes oficiais
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<HSVColor> NamedColors
		{
			get
			{
				return new HSVColor[]
					{
  						new HSVColor("#0048BA","Absolute Zero"),
  						new HSVColor("#B0BF1A","Acid green"),
  						new HSVColor("#7CB9E8","Aero"),
  						new HSVColor("#C0E8D5","Aero blue"),
  						new HSVColor("#B284BE","African violet"),
  						new HSVColor("#72A0C1","Air superiority blue"),
  						new HSVColor("#EDEAE0","Alabaster"),
  						new HSVColor("#F0F8FF","Alice blue"),
  						new HSVColor("#C46210","Alloy orange"),
  						new HSVColor("#EFDECD","Almond"),
  						new HSVColor("#E52B50","Amaranth"),
  						new HSVColor("#9F2B68","Amaranth (M&P)"),
  						new HSVColor("#F19CBB","Amaranth pink"),
  						new HSVColor("#AB274F","Amaranth purple"),
  						new HSVColor("#D3212D","Amaranth red"),
  						new HSVColor("#3B7A57","Amazon"),
  						new HSVColor("#FFBF00","Amber"),
  						new HSVColor("#FF7E00","Amber (SAE/ECE)"),
  						new HSVColor("#9966CC","Amethyst"),
  						new HSVColor("#3DDC84","Android green"),
  						new HSVColor("#CD9575","Antique brass"),
  						new HSVColor("#665D1E","Antique bronze"),
  						new HSVColor("#915C83","Antique fuchsia"),
  						new HSVColor("#841B2D","Antique ruby"),
  						new HSVColor("#FAEBD7","Antique white"),
  						new HSVColor("#008000","Ao (English)"),
  						new HSVColor("#8DB600","Apple green"),
  						new HSVColor("#FBCEB1","Apricot"),
  						new HSVColor("#00FFFF","Aqua"),
  						new HSVColor("#7FFFD4","Aquamarine"),
  						new HSVColor("#D0FF14","Arctic lime"),
  						new HSVColor("#4B5320","Army green"),
  						new HSVColor("#8F9779","Artichoke"),
  						new HSVColor("#E9D66B","Arylide yellow"),
  						new HSVColor("#B2BEB5","Ash gray"),
  						new HSVColor("#87A96B","Asparagus"),
  						new HSVColor("#FF9966","Atomic tangerine"),
  						new HSVColor("#A52A2A","Auburn"),
  						new HSVColor("#FDEE00","Aureolin"),
  						new HSVColor("#568203","Avocado"),
  						new HSVColor("#007FFF","Azure"),
  						new HSVColor("#F0FFFF","Azure (X11/web color)"),
  						new HSVColor("#89CFF0","Baby blue"),
  						new HSVColor("#A1CAF1","Baby blue eyes"),
  						new HSVColor("#F4C2C2","Baby pink"),
  						new HSVColor("#FEFEFA","Baby powder"),
  						new HSVColor("#FF91AF","Baker-Miller pink"),
  						new HSVColor("#FAE7B5","Banana Mania"),
  						new HSVColor("#DA1884","Barbie Pink"),
  						new HSVColor("#7C0A02","Barn red"),
  						new HSVColor("#848482","Battleship grey"),
  						new HSVColor("#BCD4E6","Beau blue"),
  						new HSVColor("#9F8170","Beaver"),
  						new HSVColor("#F5F5DC","Beige"),
	  					new HSVColor("#2E5894","B'dazzled blue"),
	  					new HSVColor("#9C2542","Big dip o'ruby"),
	  					new HSVColor("#FFE4C4","Bisque"),
  						new HSVColor("#3D2B1F","Bistre"),
  						new HSVColor("#967117","Bistre brown"),
  						new HSVColor("#CAE00D","Bitter lemon"),
  						new HSVColor("#BFFF00","Bitter lime"),
  						new HSVColor("#FE6F5E","Bittersweet"),
  						new HSVColor("#BF4F51","Bittersweet shimmer"),
  						new HSVColor("#000000","Black"),
  						new HSVColor("#3D0C02","Black bean"),
  						new HSVColor("#1B1811","Black chocolate"),
  						new HSVColor("#3B2F2F","Black coffee"),
  						new HSVColor("#54626F","Black coral"),
  						new HSVColor("#3B3C36","Black olive"),
  						new HSVColor("#BFAFB2","Black Shadows"),
  						new HSVColor("#FFEBCD","Blanched almond"),
  						new HSVColor("#A57164","Blast-off bronze"),
  						new HSVColor("#318CE7","Bleu de France"),
  						new HSVColor("#ACE5EE","Blizzard blue"),
  						new HSVColor("#FAF0BE","Blond"),
  						new HSVColor("#660000","Blood red"),
  						new HSVColor("#0000FF","Blue"),
  						new HSVColor("#1F75FE","Blue (Crayola)"),
  						new HSVColor("#0093AF","Blue (Munsell)"),
  						new HSVColor("#0087BD","Blue (NCS)"),
  						new HSVColor("#0018A8","Blue (Pantone)"),
  						new HSVColor("#333399","Blue (pigment)"),
  						new HSVColor("#0247FE","Blue (RYB)"),
  						new HSVColor("#A2A2D0","Blue bell"),
  						new HSVColor("#6699CC","Blue-gray"),
  						new HSVColor("#0D98BA","Blue-green"),
  						new HSVColor("#064E40","Blue-green (color wheel)"),
  						new HSVColor("#5DADEC","Blue jeans"),
  						new HSVColor("#126180","Blue sapphire"),
  						new HSVColor("#8A2BE2","Blue-violet"),
  						new HSVColor("#7366BD","Blue-violet (Crayola)"),
  						new HSVColor("#4D1A7F","Blue-violet (color wheel)"),
  						new HSVColor("#5072A7","Blue yonder"),
  						new HSVColor("#3C69E7","Bluetiful"),
  						new HSVColor("#DE5D83","Blush"),
  						new HSVColor("#79443B","Bole"),
  						new HSVColor("#E3DAC9","Bone"),
  						new HSVColor("#006A4E","Bottle green"),
  						new HSVColor("#87413F","Brandy"),
  						new HSVColor("#CB4154","Brick red"),
  						new HSVColor("#66FF00","Bright green"),
  						new HSVColor("#D891EF","Bright lilac"),
  						new HSVColor("#C32148","Bright maroon"),
  						new HSVColor("#1974D2","Bright navy blue"),
  						new HSVColor("#FFAA1D","Bright yellow (Crayola)"),
  						new HSVColor("#FF55A3","Brilliant rose"),
  						new HSVColor("#FB607F","Brink pink"),
  						new HSVColor("#004225","British racing green"),
  						new HSVColor("#CD7F32","Bronze"),
  						new HSVColor("#88540B","Brown"),
  						new HSVColor("#AF6E4D","Brown sugar"),
  						new HSVColor("#1B4D3E","Brunswick green"),
  						new HSVColor("#7BB661","Bud green"),
  						new HSVColor("#FFC680","Buff"),
  						new HSVColor("#800020","Burgundy"),
  						new HSVColor("#DEB887","Burlywood"),
  						new HSVColor("#A17A74","Burnished brown"),
  						new HSVColor("#CC5500","Burnt orange"),
  						new HSVColor("#E97451","Burnt sienna"),
  						new HSVColor("#8A3324","Burnt umber"),
  						new HSVColor("#BD33A4","Byzantine"),
  						new HSVColor("#702963","Byzantium"),
  						new HSVColor("#536872","Cadet"),
  						new HSVColor("#5F9EA0","Cadet blue"),
  						new HSVColor("#A9B2C3","Cadet blue (Crayola)"),
  						new HSVColor("#91A3B0","Cadet grey"),
  						new HSVColor("#006B3C","Cadmium green"),
  						new HSVColor("#ED872D","Cadmium orange"),
  						new HSVColor("#E30022","Cadmium red"),
  						new HSVColor("#FFF600","Cadmium yellow"),
  						new HSVColor("#A67B5B","Café au lait"),
  						new HSVColor("#4B3621","Café noir"),
  						new HSVColor("#A3C1AD","Cambridge blue"),
  						new HSVColor("#C19A6B","Camel"),
  						new HSVColor("#EFBBCC","Cameo pink"),
  						new HSVColor("#FFFF99","Canary"),
  						new HSVColor("#FFEF00","Canary yellow"),
  						new HSVColor("#FF0800","Candy apple red"),
  						new HSVColor("#E4717A","Candy pink"),
  						new HSVColor("#00BFFF","Capri"),
  						new HSVColor("#592720","Caput mortuum"),
  						new HSVColor("#C41E3A","Cardinal"),
  						new HSVColor("#00CC99","Caribbean green"),
  						new HSVColor("#960018","Carmine"),
  						new HSVColor("#D70040","Carmine (M&P)"),
  						new HSVColor("#FFA6C9","Carnation pink"),
  						new HSVColor("#B31B1B","Carnelian"),
  						new HSVColor("#56A0D3","Carolina blue"),
  						new HSVColor("#ED9121","Carrot orange"),
  						new HSVColor("#00563F","Castleton green"),
  						new HSVColor("#703642","Catawba"),
  						new HSVColor("#C95A49","Cedar Chest"),
  						new HSVColor("#ACE1AF","Celadon"),
  						new HSVColor("#007BA7","Celadon blue"),
  						new HSVColor("#2F847C","Celadon green"),
  						new HSVColor("#B2FFFF","Celeste"),
  						new HSVColor("#246BCE","Celtic blue"),
  						new HSVColor("#DE3163","Cerise"),
  						new HSVColor("#007BA7","Cerulean"),
  						new HSVColor("#2A52BE","Cerulean blue"),
  						new HSVColor("#6D9BC3","Cerulean frost"),
  						new HSVColor("#1DACD6","Cerulean (Crayola)"),
  						new HSVColor("#007AA5","CG blue"),
  						new HSVColor("#E03C31","CG red"),
  						new HSVColor("#F7E7CE","Champagne"),
  						new HSVColor("#F1DDCF","Champagne pink"),
  						new HSVColor("#36454F","Charcoal"),
  						new HSVColor("#232B2B","Charleston green"),
  						new HSVColor("#E68FAC","Charm pink"),
  						new HSVColor("#DFFF00","Chartreuse (traditional)"),
  						new HSVColor("#7FFF00","Chartreuse (web)"),
  						new HSVColor("#FFB7C5","Cherry blossom pink"),
  						new HSVColor("#954535","Chestnut"),
  						new HSVColor("#E23D28","Chili red"),
  						new HSVColor("#DE6FA1","China pink"),
  						new HSVColor("#A8516E","China rose"),
  						new HSVColor("#AA381E","Chinese red"),
  						new HSVColor("#856088","Chinese violet"),
  						new HSVColor("#FFB200","Chinese yellow"),
  						new HSVColor("#7B3F00","Chocolate (traditional)"),
  						new HSVColor("#D2691E","Chocolate (web)"),
  						new HSVColor("#58111A","Chocolate Cosmos"),
  						new HSVColor("#FFA700","Chrome yellow"),
  						new HSVColor("#98817B","Cinereous"),
  						new HSVColor("#E34234","Cinnabar"),
  						new HSVColor("#CD607E","Cinnamon Satin"),
  						new HSVColor("#E4D00A","Citrine"),
  						new HSVColor("#9FA91F","Citron"),
  						new HSVColor("#7F1734","Claret"),
  						new HSVColor("#0047AB","Cobalt blue"),
  						new HSVColor("#D2691E","Cocoa brown"),
  						new HSVColor("#6F4E37","Coffee"),
  						new HSVColor("#B9D9EB","Columbia Blue"),
  						new HSVColor("#F88379","Congo pink"),
  						new HSVColor("#8C92AC","Cool grey"),
  						new HSVColor("#B87333","Copper"),
  						new HSVColor("#DA8A67","Copper (Crayola)"),
  						new HSVColor("#AD6F69","Copper penny"),
  						new HSVColor("#CB6D51","Copper red"),
  						new HSVColor("#996666","Copper rose"),
  						new HSVColor("#FF3800","Coquelicot"),
  						new HSVColor("#FF7F50","Coral"),
  						new HSVColor("#F88379","Coral pink"),
  						new HSVColor("#893F45","Cordovan"),
  						new HSVColor("#FBEC5D","Corn"),
  						new HSVColor("#B31B1B","Cornell red"),
  						new HSVColor("#6495ED","Cornflower blue"),
  						new HSVColor("#FFF8DC","Cornsilk"),
  						new HSVColor("#2E2D88","Cosmic cobalt"),
  						new HSVColor("#FFF8E7","Cosmic latte"),
  						new HSVColor("#81613C","Coyote brown"),
  						new HSVColor("#FFBCD9","Cotton candy"),
  						new HSVColor("#FFFDD0","Cream"),
  						new HSVColor("#DC143C","Crimson"),
  						new HSVColor("#9E1B32","Crimson (UA)"),
  						new HSVColor("#A7D8DE","Crystal"),
  						new HSVColor("#F5F5F5","Cultured"),
  						new HSVColor("#00FFFF","Cyan"),
  						new HSVColor("#00B7EB","Cyan (process)"),
  						new HSVColor("#58427C","Cyber grape"),
  						new HSVColor("#FFD300","Cyber yellow"),
  						new HSVColor("#F56FA1","Cyclamen"),
  						new HSVColor("#666699","Dark blue-gray"),
  						new HSVColor("#654321","Dark brown"),
  						new HSVColor("#5D3954","Dark byzantium"),
  						new HSVColor("#26428B","Dark cornflower blue"),
  						new HSVColor("#008B8B","Dark cyan"),
  						new HSVColor("#536878","Dark electric blue"),
  						new HSVColor("#B8860B","Dark goldenrod"),
  						new HSVColor("#013220","Dark green"),
  						new HSVColor("#006400","Dark green (X11)"),
  						new HSVColor("#1A2421","Dark jungle green"),
  						new HSVColor("#BDB76B","Dark khaki"),
  						new HSVColor("#483C32","Dark lava"),
  						new HSVColor("#534B4F","Dark liver"),
  						new HSVColor("#543D37","Dark liver (horses)"),
  						new HSVColor("#8B008B","Dark magenta"),
  						new HSVColor("#4A5D23","Dark moss green"),
  						new HSVColor("#556B2F","Dark olive green"),
  						new HSVColor("#FF8C00","Dark orange"),
  						new HSVColor("#9932CC","Dark orchid"),
  						new HSVColor("#03C03C","Dark pastel green"),
  						new HSVColor("#301934","Dark purple"),
  						new HSVColor("#8B0000","Dark red"),
  						new HSVColor("#E9967A","Dark salmon"),
  						new HSVColor("#8FBC8F","Dark sea green"),
  						new HSVColor("#3C1414","Dark sienna"),
  						new HSVColor("#8CBED6","Dark sky blue"),
  						new HSVColor("#483D8B","Dark slate blue"),
  						new HSVColor("#2F4F4F","Dark slate gray"),
  						new HSVColor("#177245","Dark spring green"),
  						new HSVColor("#00CED1","Dark turquoise"),
  						new HSVColor("#9400D3","Dark violet"),
  						new HSVColor("#00703C","Dartmouth green"),
  						new HSVColor("#555555","Davy's grey"),
  						new HSVColor("#DA3287","Deep cerise"),
  						new HSVColor("#FAD6A5","Deep champagne"),
  						new HSVColor("#B94E48","Deep chestnut"),
  						new HSVColor("#004B49","Deep jungle green"),
  						new HSVColor("#FF1493","Deep pink"),
  						new HSVColor("#FF9933","Deep saffron"),
  						new HSVColor("#00BFFF","Deep sky blue"),
  						new HSVColor("#4A646C","Deep Space Sparkle"),
  						new HSVColor("#7E5E60","Deep taupe"),
  						new HSVColor("#1560BD","Denim"),
  						new HSVColor("#2243B6","Denim blue"),
  						new HSVColor("#C19A6B","Desert"),
  						new HSVColor("#EDC9AF","Desert sand"),
  						new HSVColor("#696969","Dim gray"),
  						new HSVColor("#1E90FF","Dodger blue"),
  						new HSVColor("#D71868","Dogwood rose"),
  						new HSVColor("#967117","Drab"),
  						new HSVColor("#00009C","Duke blue"),
  						new HSVColor("#EFDFBB","Dutch white"),
  						new HSVColor("#E1A95F","Earth yellow"),
  						new HSVColor("#555D50","Ebony"),
  						new HSVColor("#C2B280","Ecru"),
  						new HSVColor("#1B1B1B","Eerie black"),
  						new HSVColor("#614051","Eggplant"),
  						new HSVColor("#F0EAD6","Eggshell"),
  						new HSVColor("#1034A6","Egyptian blue"),
  						new HSVColor("#16161D","Eigengrau"),
  						new HSVColor("#7DF9FF","Electric blue"),
  						new HSVColor("#00FF00","Electric green"),
  						new HSVColor("#6F00FF","Electric indigo"),
  						new HSVColor("#CCFF00","Electric lime"),
  						new HSVColor("#BF00FF","Electric purple"),
  						new HSVColor("#8F00FF","Electric violet"),
  						new HSVColor("#50C878","Emerald"),
  						new HSVColor("#6C3082","Eminence"),
  						new HSVColor("#1B4D3E","English green"),
  						new HSVColor("#B48395","English lavender"),
  						new HSVColor("#AB4B52","English red"),
  						new HSVColor("#CC474B","English vermillion"),
  						new HSVColor("#563C5C","English violet"),
  						new HSVColor("#00FF40","Erin"),
  						new HSVColor("#96C8A2","Eton blue"),
  						new HSVColor("#C19A6B","Fallow"),
  						new HSVColor("#801818","Falu red"),
  						new HSVColor("#B53389","Fandango"),
  						new HSVColor("#DE5285","Fandango pink"),
  						new HSVColor("#F400A1","Fashion fuchsia"),
  						new HSVColor("#E5AA70","Fawn"),
  						new HSVColor("#4D5D53","Feldgrau"),
  						new HSVColor("#4F7942","Fern green"),
  						new HSVColor("#6C541E","Field drab"),
  						new HSVColor("#FF5470","Fiery rose"),
  						new HSVColor("#B22222","Firebrick"),
  						new HSVColor("#CE2029","Fire engine red"),
  						new HSVColor("#E95C4B","Fire opal"),
  						new HSVColor("#E25822","Flame"),
  						new HSVColor("#EEDC82","Flax"),
  						new HSVColor("#A2006D","Flirt"),
  						new HSVColor("#FFFAF0","Floral white"),
  						new HSVColor("#15F4EE","Fluorescent blue"),
  						new HSVColor("#5FA777","Forest green (Crayola)"),
  						new HSVColor("#014421","Forest green (traditional)"),
  						new HSVColor("#228B22","Forest green (web)"),
  						new HSVColor("#A67B5B","French beige"),
  						new HSVColor("#856D4D","French bistre"),
  						new HSVColor("#0072BB","French blue"),
  						new HSVColor("#FD3F92","French fuchsia"),
  						new HSVColor("#86608E","French lilac"),
  						new HSVColor("#9EFD38","French lime"),
  						new HSVColor("#D473D4","French mauve"),
  						new HSVColor("#FD6C9E","French pink"),
  						new HSVColor("#C72C48","French raspberry"),
  						new HSVColor("#F64A8A","French rose"),
  						new HSVColor("#77B5FE","French sky blue"),
  						new HSVColor("#8806CE","French violet"),
  						new HSVColor("#E936A7","Frostbite"),
  						new HSVColor("#FF00FF","Fuchsia"),
  						new HSVColor("#C154C1","Fuchsia (Crayola)"),
  						new HSVColor("#CC397B","Fuchsia purple"),
  						new HSVColor("#C74375","Fuchsia rose"),
  						new HSVColor("#E48400","Fulvous"),
  						new HSVColor("#87421F","Fuzzy Wuzzy"),
  						new HSVColor("#DCDCDC","Gainsboro"),
  						new HSVColor("#E49B0F","Gamboge"),
  						new HSVColor("#007F66","Generic viridian"),
  						new HSVColor("#F8F8FF","Ghost white"),
  						new HSVColor("#6082B6","Glaucous"),
  						new HSVColor("#AB92B3","Glossy grape"),
  						new HSVColor("#00AB66","GO green"),
  						new HSVColor("#A57C00","Gold"),
  						new HSVColor("#D4AF37","Gold (metallic)"),
  						new HSVColor("#FFD700","Gold (web) (Golden)"),
  						new HSVColor("#E6BE8A","Gold (Crayola)"),
  						new HSVColor("#85754E","Gold Fusion"),
  						new HSVColor("#996515","Golden brown"),
  						new HSVColor("#FCC200","Golden poppy"),
  						new HSVColor("#FFDF00","Golden yellow"),
  						new HSVColor("#DAA520","Goldenrod"),
  						new HSVColor("#00573F","Gotham green"),
  						new HSVColor("#676767","Granite gray"),
  						new HSVColor("#A8E4A0","Granny Smith apple"),
  						new HSVColor("#808080","Gray (web)"),
  						new HSVColor("#BEBEBE","Gray (X11 gray)"),
  						new HSVColor("#00FF00","Green"),
  						new HSVColor("#1CAC78","Green (Crayola)"),
  						new HSVColor("#008000","Green (web)"),
  						new HSVColor("#00A877","Green (Munsell)"),
  						new HSVColor("#009F6B","Green (NCS)"),
  						new HSVColor("#00AD43","Green (Pantone)"),
  						new HSVColor("#00A550","Green (pigment)"),
  						new HSVColor("#66B032","Green (RYB)"),
  						new HSVColor("#1164B4","Green-blue"),
  						new HSVColor("#2887C8","Green-blue (Crayola)"),
  						new HSVColor("#009966","Green-cyan"),
  						new HSVColor("#A7F432","Green Lizard"),
  						new HSVColor("#6EAEA1","Green Sheen"),
  						new HSVColor("#ADFF2F","Green-yellow"),
  						new HSVColor("#F0E891","Green-yellow (Crayola)"),
  						new HSVColor("#A99A86","Grullo"),
  						new HSVColor("#2A3439","Gunmetal"),
  						new HSVColor("#446CCF","Han blue"),
  						new HSVColor("#5218FA","Han purple"),
  						new HSVColor("#E9D66B","Hansa yellow"),
  						new HSVColor("#3FFF00","Harlequin"),
  						new HSVColor("#DA9100","Harvest gold"),
  						new HSVColor("#FF7A00","Heat Wave"),
  						new HSVColor("#DF73FF","Heliotrope"),
  						new HSVColor("#AA98A9","Heliotrope gray"),
  						new HSVColor("#F400A1","Hollywood cerise"),
  						new HSVColor("#F0FFF0","Honeydew"),
  						new HSVColor("#006DB0","Honolulu blue"),
  						new HSVColor("#49796B","Hooker's green"),
  						new HSVColor("#FF1DCE","Hot magenta"),
  						new HSVColor("#FF69B4","Hot pink"),
  						new HSVColor("#355E3B","Hunter green"),
  						new HSVColor("#71A6D2","Iceberg"),
  						new HSVColor("#FCF75E","Icterine"),
  						new HSVColor("#319177","Illuminating emerald"),
  						new HSVColor("#ED2939","Imperial red"),
  						new HSVColor("#B2EC5D","Inchworm"),
  						new HSVColor("#4C516D","Independence"),
  						new HSVColor("#138808","India green"),
  						new HSVColor("#CD5C5C","Indian red"),
  						new HSVColor("#E3A857","Indian yellow"),
  						new HSVColor("#4B0082","Indigo"),
  						new HSVColor("#00416A","Indigo dye"),
  						new HSVColor("#130A8F","International Klein Blue"),
  						new HSVColor("#FF4F00","International orange (aerospace)"),
  						new HSVColor("#BA160C","International orange (engineering)"),
  						new HSVColor("#C0362C","International orange (Golden Gate Bridge)"),
  						new HSVColor("#5A4FCF","Iris"),
  						new HSVColor("#B3446C","Irresistible"),
  						new HSVColor("#F4F0EC","Isabelline"),
  						new HSVColor("#B2FFFF","Italian sky blue"),
  						new HSVColor("#FFFFF0","Ivory"),
  						new HSVColor("#00A86B","Jade"),
  						new HSVColor("#9D2933","Japanese carmine"),
  						new HSVColor("#5B3256","Japanese violet"),
  						new HSVColor("#F8DE7E","Jasmine"),
  						new HSVColor("#A50B5E","Jazzberry jam"),
  						new HSVColor("#343434","Jet"),
  						new HSVColor("#F4CA16","Jonquil"),
  						new HSVColor("#BDDA57","June bud"),
  						new HSVColor("#29AB87","Jungle green"),
  						new HSVColor("#4CBB17","Kelly green"),
  						new HSVColor("#3AB09E","Keppel"),
  						new HSVColor("#E8F48C","Key lime"),
  						new HSVColor("#C3B091","Khaki (web)"),
  						new HSVColor("#F0E68C","Khaki (X11) (Light khaki)"),
  						new HSVColor("#882D17","Kobe"),
  						new HSVColor("#E79FC4","Kobi"),
  						new HSVColor("#6B4423","Kobicha"),
  						new HSVColor("#354230","Kombu green"),
  						new HSVColor("#512888","KSU purple"),
  						new HSVColor("#D6CADD","Languid lavender"),
  						new HSVColor("#26619C","Lapis lazuli"),
  						new HSVColor("#FFFF66","Laser lemon"),
  						new HSVColor("#A9BA9D","Laurel green"),
  						new HSVColor("#CF1020","Lava"),
  						new HSVColor("#B57EDC","Lavender (floral)"),
  						new HSVColor("#E6E6FA","Lavender (web)"),
  						new HSVColor("#CCCCFF","Lavender blue"),
  						new HSVColor("#FFF0F5","Lavender blush"),
  						new HSVColor("#C4C3D0","Lavender gray"),
  						new HSVColor("#7CFC00","Lawn green"),
  						new HSVColor("#FFF700","Lemon"),
  						new HSVColor("#FFFACD","Lemon chiffon"),
  						new HSVColor("#CCA01D","Lemon curry"),
  						new HSVColor("#FDFF00","Lemon glacier"),
  						new HSVColor("#F6EABE","Lemon meringue"),
  						new HSVColor("#FFF44F","Lemon yellow"),
  						new HSVColor("#FFFF9F","Lemon yellow (Crayola)"),
  						new HSVColor("#545AA7","Liberty"),
  						new HSVColor("#ADD8E6","Light blue"),
  						new HSVColor("#F08080","Light coral"),
  						new HSVColor("#93CCEA","Light cornflower blue"),
  						new HSVColor("#E0FFFF","Light cyan"),
  						new HSVColor("#C8AD7F","Light French beige"),
  						new HSVColor("#FAFAD2","Light goldenrod yellow"),
  						new HSVColor("#D3D3D3","Light gray"),
  						new HSVColor("#90EE90","Light green"),
  						new HSVColor("#FED8B1","Light orange"),
  						new HSVColor("#C5CBE1","Light periwinkle"),
  						new HSVColor("#FFB6C1","Light pink"),
  						new HSVColor("#FFA07A","Light salmon"),
  						new HSVColor("#20B2AA","Light sea green"),
  						new HSVColor("#87CEFA","Light sky blue"),
  						new HSVColor("#778899","Light slate gray"),
  						new HSVColor("#B0C4DE","Light steel blue"),
  						new HSVColor("#FFFFE0","Light yellow"),
  						new HSVColor("#C8A2C8","Lilac"),
  						new HSVColor("#AE98AA","Lilac Luster"),
  						new HSVColor("#BFFF00","Lime (color wheel)"),
  						new HSVColor("#00FF00","Lime (web) (X11 green)"),
  						new HSVColor("#32CD32","Lime green"),
  						new HSVColor("#195905","Lincoln green"),
  						new HSVColor("#FAF0E6","Linen"),
  						new HSVColor("#C19A6B","Lion"),
  						new HSVColor("#DE6FA1","Liseran purple"),
  						new HSVColor("#6CA0DC","Little boy blue"),
  						new HSVColor("#674C47","Liver"),
  						new HSVColor("#B86D29","Liver (dogs)"),
  						new HSVColor("#6C2E1F","Liver (organ)"),
  						new HSVColor("#987456","Liver chestnut"),
  						new HSVColor("#6699CC","Livid"),
  						new HSVColor("#FFBD88","Macaroni and Cheese"),
  						new HSVColor("#CC3336","Madder Lake"),
  						new HSVColor("#FF00FF","Magenta"),
  						new HSVColor("#F653A6","Magenta (Crayola)"),
  						new HSVColor("#CA1F7B","Magenta (dye)"),
  						new HSVColor("#D0417E","Magenta (Pantone)"),
  						new HSVColor("#FF0090","Magenta (process)"),
  						new HSVColor("#9F4576","Magenta haze"),
  						new HSVColor("#AAF0D1","Magic mint"),
  						new HSVColor("#F2E8D7","Magnolia"),
  						new HSVColor("#C04000","Mahogany"),
  						new HSVColor("#FBEC5D","Maize"),
  						new HSVColor("#F2C649","Maize (Crayola)"),
  						new HSVColor("#6050DC","Majorelle blue"),
  						new HSVColor("#0BDA51","Malachite"),
  						new HSVColor("#979AAA","Manatee"),
  						new HSVColor("#F37A48","Mandarin"),
  						new HSVColor("#FDBE02","Mango"),
  						new HSVColor("#FF8243","Mango Tango"),
  						new HSVColor("#74C365","Mantis"),
  						new HSVColor("#880085","Mardi Gras"),
  						new HSVColor("#EAA221","Marigold"),
  						new HSVColor("#C32148","Maroon (Crayola)"),
  						new HSVColor("#800000","Maroon (web)"),
  						new HSVColor("#B03060","Maroon (X11)"),
  						new HSVColor("#E0B0FF","Mauve"),
  						new HSVColor("#915F6D","Mauve taupe"),
  						new HSVColor("#EF98AA","Mauvelous"),
  						new HSVColor("#47ABCC","Maximum blue"),
  						new HSVColor("#30BFBF","Maximum blue green"),
  						new HSVColor("#ACACE6","Maximum blue purple"),
  						new HSVColor("#5E8C31","Maximum green"),
  						new HSVColor("#D9E650","Maximum green yellow"),
  						new HSVColor("#733380","Maximum purple"),
  						new HSVColor("#D92121","Maximum red"),
  						new HSVColor("#A63A79","Maximum red purple"),
  						new HSVColor("#FAFA37","Maximum yellow"),
  						new HSVColor("#F2BA49","Maximum yellow red"),
  						new HSVColor("#4C9141","May green"),
  						new HSVColor("#73C2FB","Maya blue"),
  						new HSVColor("#66DDAA","Medium aquamarine"),
  						new HSVColor("#0000CD","Medium blue"),
  						new HSVColor("#E2062C","Medium candy apple red"),
  						new HSVColor("#AF4035","Medium carmine"),
  						new HSVColor("#F3E5AB","Medium champagne"),
  						new HSVColor("#BA55D3","Medium orchid"),
  						new HSVColor("#9370DB","Medium purple"),
  						new HSVColor("#3CB371","Medium sea green"),
  						new HSVColor("#7B68EE","Medium slate blue"),
  						new HSVColor("#00FA9A","Medium spring green"),
  						new HSVColor("#48D1CC","Medium turquoise"),
  						new HSVColor("#C71585","Medium violet-red"),
  						new HSVColor("#F8B878","Mellow apricot"),
  						new HSVColor("#F8DE7E","Mellow yellow"),
  						new HSVColor("#FEBAAD","Melon"),
  						new HSVColor("#D3AF37","Metallic gold"),
  						new HSVColor("#0A7E8C","Metallic Seaweed"),
  						new HSVColor("#9C7C38","Metallic Sunburst"),
  						new HSVColor("#E4007C","Mexican pink"),
  						new HSVColor("#7ED4E6","Middle blue"),
  						new HSVColor("#8DD9CC","Middle blue green"),
  						new HSVColor("#8B72BE","Middle blue purple"),
  						new HSVColor("#8B8680","Middle grey"),
  						new HSVColor("#4D8C57","Middle green"),
  						new HSVColor("#ACBF60","Middle green yellow"),
  						new HSVColor("#D982B5","Middle purple"),
  						new HSVColor("#E58E73","Middle red"),
  						new HSVColor("#A55353","Middle red purple"),
  						new HSVColor("#FFEB00","Middle yellow"),
  						new HSVColor("#ECB176","Middle yellow red"),
  						new HSVColor("#702670","Midnight"),
  						new HSVColor("#191970","Midnight blue"),
  						new HSVColor("#004953","Midnight green (eagle green)"),
  						new HSVColor("#FFC40C","Mikado yellow"),
  						new HSVColor("#FFDAE9","Mimi pink"),
  						new HSVColor("#E3F988","Mindaro"),
  						new HSVColor("#36747D","Ming"),
  						new HSVColor("#F5E050","Minion yellow"),
  						new HSVColor("#3EB489","Mint"),
  						new HSVColor("#F5FFFA","Mint cream"),
  						new HSVColor("#98FF98","Mint green"),
  						new HSVColor("#BBB477","Misty moss"),
  						new HSVColor("#FFE4E1","Misty rose"),
  						new HSVColor("#967117","Mode beige"),
  						new HSVColor("#8DA399","Morning blue"),
  						new HSVColor("#8A9A5B","Moss green"),
  						new HSVColor("#30BA8F","Mountain Meadow"),
  						new HSVColor("#997A8D","Mountbatten pink"),
  						new HSVColor("#18453B","MSU green"),
  						new HSVColor("#C54B8C","Mulberry"),
  						new HSVColor("#C8509B","Mulberry (Crayola)"),
  						new HSVColor("#FFDB58","Mustard"),
  						new HSVColor("#317873","Myrtle green"),
  						new HSVColor("#D65282","Mystic"),
  						new HSVColor("#AD4379","Mystic maroon"),
  						new HSVColor("#F6ADC6","Nadeshiko pink"),
  						new HSVColor("#FADA5E","Naples yellow"),
  						new HSVColor("#FFDEAD","Navajo white"),
  						new HSVColor("#000080","Navy blue"),
  						new HSVColor("#1974D2","Navy blue (Crayola)"),
  						new HSVColor("#4666FF","Neon blue"),
  						new HSVColor("#FFA343","Neon Carrot"),
  						new HSVColor("#39FF14","Neon green"),
  						new HSVColor("#FE4164","Neon fuchsia"),
  						new HSVColor("#D7837F","New York pink"),
  						new HSVColor("#727472","Nickel"),
  						new HSVColor("#A4DDED","Non-photo blue"),
  						new HSVColor("#E9FFDB","Nyanza"),
  						new HSVColor("#4F42B5","Ocean Blue"),
  						new HSVColor("#48BF91","Ocean green"),
  						new HSVColor("#CC7722","Ochre"),
  						new HSVColor("#43302E","Old burgundy"),
  						new HSVColor("#CFB53B","Old gold"),
  						new HSVColor("#FDF5E6","Old lace"),
  						new HSVColor("#796878","Old lavender"),
  						new HSVColor("#673147","Old mauve"),
  						new HSVColor("#C08081","Old rose"),
  						new HSVColor("#848482","Old silver"),
  						new HSVColor("#808000","Olive"),
  						new HSVColor("#6B8E23","Olive Drab (#3)"),
  						new HSVColor("#3C341F","Olive Drab #7"),
  						new HSVColor("#B5B35C","Olive green"),
  						new HSVColor("#9AB973","Olivine"),
  						new HSVColor("#353839","Onyx"),
  						new HSVColor("#A8C3BC","Opal"),
  						new HSVColor("#B784A7","Opera mauve"),
  						new HSVColor("#FF7F00","Orange"),
  						new HSVColor("#FF7538","Orange (Crayola)"),
  						new HSVColor("#FF5800","Orange (Pantone)"),
  						new HSVColor("#FFA500","Orange (web)"),
  						new HSVColor("#FF9F00","Orange peel"),
  						new HSVColor("#FF681F","Orange-red"),
  						new HSVColor("#FF5349","Orange-red (Crayola)"),
  						new HSVColor("#FA5B3D","Orange soda"),
  						new HSVColor("#F5BD1F","Orange-yellow"),
  						new HSVColor("#F8D568","Orange-yellow (Crayola)"),
  						new HSVColor("#DA70D6","Orchid"),
  						new HSVColor("#F2BDCD","Orchid pink"),
  						new HSVColor("#E29CD2","Orchid (Crayola)"),
  						new HSVColor("#2D383A","Outer space (Crayola)"),
  						new HSVColor("#FF6E4A","Outrageous Orange"),
  						new HSVColor("#4A0000","Oxblood"),
  						new HSVColor("#002147","Oxford blue"),
  						new HSVColor("#841617","OU Crimson red"),
  						new HSVColor("#1CA9C9","Pacific blue"),
  						new HSVColor("#006600","Pakistan green"),
  						new HSVColor("#682860","Palatinate purple"),
  						new HSVColor("#BCD4E6","Pale aqua"),
  						new HSVColor("#9BC4E2","Pale cerulean"),
  						new HSVColor("#ED7A9B","Pale Dogwood"),
  						new HSVColor("#FADADD","Pale pink"),
  						new HSVColor("#FAE6FA","Pale purple (Pantone)"),
  						new HSVColor("#C9C0BB","Pale silver"),
  						new HSVColor("#ECEBBD","Pale spring bud"),
  						new HSVColor("#78184A","Pansy purple"),
  						new HSVColor("#009B7D","Paolo Veronese green"),
  						new HSVColor("#FFEFD5","Papaya whip"),
  						new HSVColor("#E63E62","Paradise pink"),
  						new HSVColor("#F1E9D2","Parchment"),
  						new HSVColor("#50C878","Paris Green"),
  						new HSVColor("#DEA5A4","Pastel pink"),
  						new HSVColor("#800080","Patriarch"),
  						new HSVColor("#536878","Payne's grey"),
  						new HSVColor("#FFE5B4","Peach"),
  						new HSVColor("#FFCBA4","Peach (Crayola)"),
  						new HSVColor("#FFDAB9","Peach puff"),
  						new HSVColor("#D1E231","Pear"),
  						new HSVColor("#B768A2","Pearly purple"),
  						new HSVColor("#CCCCFF","Periwinkle"),
  						new HSVColor("#C3CDE6","Periwinkle (Crayola)"),
  						new HSVColor("#E12C2C","Permanent Geranium Lake"),
  						new HSVColor("#1C39BB","Persian blue"),
  						new HSVColor("#00A693","Persian green"),
  						new HSVColor("#32127A","Persian indigo"),
  						new HSVColor("#D99058","Persian orange"),
  						new HSVColor("#F77FBE","Persian pink"),
  						new HSVColor("#701C1C","Persian plum"),
  						new HSVColor("#CC3333","Persian red"),
  						new HSVColor("#FE28A2","Persian rose"),
  						new HSVColor("#EC5800","Persimmon"),
  						new HSVColor("#8BA8B7","Pewter Blue"),
  						new HSVColor("#DF00FF","Phlox"),
  						new HSVColor("#000F89","Phthalo blue"),
  						new HSVColor("#123524","Phthalo green"),
  						new HSVColor("#2E2787","Picotee blue"),
  						new HSVColor("#C30B4E","Pictorial carmine"),
  						new HSVColor("#FDDDE6","Piggy pink"),
  						new HSVColor("#01796F","Pine green"),
  						new HSVColor("#2A2F23","Pine tree"),
  						new HSVColor("#FFC0CB","Pink"),
  						new HSVColor("#D74894","Pink (Pantone)"),
  						new HSVColor("#FC74FD","Pink flamingo"),
  						new HSVColor("#FFDDF4","Pink lace"),
  						new HSVColor("#D8B2D1","Pink lavender"),
  						new HSVColor("#F78FA7","Pink Sherbet"),
  						new HSVColor("#93C572","Pistachio"),
  						new HSVColor("#E5E4E2","Platinum"),
  						new HSVColor("#8E4585","Plum"),
  						new HSVColor("#DDA0DD","Plum (web)"),
  						new HSVColor("#5946B2","Plump Purple"),
  						new HSVColor("#5DA493","Polished Pine"),
  						new HSVColor("#86608E","Pomp and Power"),
  						new HSVColor("#BE4F62","Popstar"),
  						new HSVColor("#FF5A36","Portland Orange"),
  						new HSVColor("#B0E0E6","Powder blue"),
  						new HSVColor("#F58025","Princeton orange"),
  						new HSVColor("#FFEF00","Process yellow"),
  						new HSVColor("#701C1C","Prune"),
  						new HSVColor("#003153","Prussian blue"),
  						new HSVColor("#DF00FF","Psychedelic purple"),
  						new HSVColor("#CC8899","Puce"),
  						new HSVColor("#644117","Pullman Brown (UPS Brown)"),
  						new HSVColor("#FF7518","Pumpkin"),
  						new HSVColor("#6A0DAD","Purple"),
  						new HSVColor("#800080","Purple (web)"),
  						new HSVColor("#9F00C5","Purple (Munsell)"),
  						new HSVColor("#A020F0","Purple (X11)"),
  						new HSVColor("#9678B6","Purple mountain majesty"),
  						new HSVColor("#4E5180","Purple navy"),
  						new HSVColor("#FE4EDA","Purple pizzazz"),
  						new HSVColor("#9C51B6","Purple Plum"),
  						new HSVColor("#9A4EAE","Purpureus"),
  						new HSVColor("#436B95","Queen blue"),
  						new HSVColor("#E8CCD7","Queen pink"),
  						new HSVColor("#A6A6A6","Quick Silver"),
  						new HSVColor("#8E3A59","Quinacridone magenta"),
  						new HSVColor("#FF355E","Radical Red"),
  						new HSVColor("#242124","Raisin black"),
  						new HSVColor("#FBAB60","Rajah"),
  						new HSVColor("#E30B5D","Raspberry"),
  						new HSVColor("#915F6D","Raspberry glace"),
  						new HSVColor("#B3446C","Raspberry rose"),
  						new HSVColor("#D68A59","Raw sienna"),
  						new HSVColor("#826644","Raw umber"),
  						new HSVColor("#FF33CC","Razzle dazzle rose"),
  						new HSVColor("#E3256B","Razzmatazz"),
  						new HSVColor("#8D4E85","Razzmic Berry"),
  						new HSVColor("#663399","Rebecca Purple"),
  						new HSVColor("#FF0000","Red"),
  						new HSVColor("#EE204D","Red (Crayola)"),
  						new HSVColor("#F2003C","Red (Munsell)"),
  						new HSVColor("#C40233","Red (NCS)"),
  						new HSVColor("#ED2939","Red (Pantone)"),
  						new HSVColor("#ED1C24","Red (pigment)"),
  						new HSVColor("#FE2712","Red (RYB)"),
  						new HSVColor("#FF5349","Red-orange"),
  						new HSVColor("#FF681F","Red-orange (Crayola)"),
  						new HSVColor("#FF4500","Red-orange (name wheel)"),
  						new HSVColor("#E40078","Red-purple"),
  						new HSVColor("#FD3A4A","Red Salsa"),
  						new HSVColor("#C71585","Red-violet"),
  						new HSVColor("#C0448F","Red-violet (Crayola)"),
  						new HSVColor("#922B3E","Red-violet (name wheel)"),
  						new HSVColor("#A45A52","Redwood"),
  						new HSVColor("#002387","Resolution blue"),
  						new HSVColor("#777696","Rhythm"),
  						new HSVColor("#004040","Rich black"),
  						new HSVColor("#010B13","Rich black (FOGRA29)"),
  						new HSVColor("#010203","Rich black (FOGRA39)"),
  						new HSVColor("#444C38","Rifle green"),
  						new HSVColor("#00CCCC","Robin egg blue"),
  						new HSVColor("#8A7F80","Rocket metallic"),
  						new HSVColor("#A91101","Rojo Spanish red"),
  						new HSVColor("#838996","Roman silver"),
  						new HSVColor("#FF007F","Rose"),
  						new HSVColor("#F9429E","Rose bonbon"),
  						new HSVColor("#9E5E6F","Rose Dust"),
  						new HSVColor("#674846","Rose ebony"),
  						new HSVColor("#E32636","Rose madder"),
  						new HSVColor("#FF66CC","Rose pink"),
  						new HSVColor("#ED7A9B","Rose Pompadour"),
  						new HSVColor("#AA98A9","Rose quartz"),
  						new HSVColor("#C21E56","Rose red"),
  						new HSVColor("#905D5D","Rose taupe"),
  						new HSVColor("#AB4E52","Rose vale"),
  						new HSVColor("#65000B","Rosewood"),
  						new HSVColor("#D40000","Rosso corsa"),
  						new HSVColor("#BC8F8F","Rosy brown"),
  						new HSVColor("#002366","Royal blue (dark)"),
  						new HSVColor("#4169E1","Royal blue (light)"),
  						new HSVColor("#7851A9","Royal purple"),
  						new HSVColor("#FADA5E","Royal yellow"),
  						new HSVColor("#CE4676","Ruber"),
  						new HSVColor("#D10056","Rubine red"),
  						new HSVColor("#E0115F","Ruby"),
  						new HSVColor("#9B111E","Ruby red"),
  						new HSVColor("#A81C07","Rufous"),
  						new HSVColor("#80461B","Russet"),
  						new HSVColor("#679267","Russian green"),
  						new HSVColor("#32174D","Russian violet"),
  						new HSVColor("#B7410E","Rust"),
  						new HSVColor("#DA2C43","Rusty red"),
  						new HSVColor("#043927","Sacramento State green"),
  						new HSVColor("#8B4513","Saddle brown"),
  						new HSVColor("#FF7800","Safety orange"),
  						new HSVColor("#FF6700","Safety orange (blaze orange)"),
  						new HSVColor("#EED202","Safety yellow"),
  						new HSVColor("#F4C430","Saffron"),
  						new HSVColor("#BCB88A","Sage"),
  						new HSVColor("#23297A","St. Patrick's blue"),
  						new HSVColor("#FA8072","Salmon"),
  						new HSVColor("#FF91A4","Salmon pink"),
  						new HSVColor("#C2B280","Sand"),
  						new HSVColor("#967117","Sand dune"),
  						new HSVColor("#F4A460","Sandy brown"),
  						new HSVColor("#507D2A","Sap green"),
  						new HSVColor("#0F52BA","Sapphire"),
  						new HSVColor("#0067A5","Sapphire blue"),
  						new HSVColor("#0067A5","Sapphire (Crayola)"),
  						new HSVColor("#CBA135","Satin sheen gold"),
  						new HSVColor("#FF2400","Scarlet"),
  						new HSVColor("#FF91AF","Schauss pink"),
  						new HSVColor("#FFD800","School bus yellow"),
  						new HSVColor("#66FF66","Screamin' Green"),
  						new HSVColor("#2E8B57","Sea green"),
  						new HSVColor("#00FFCD","Sea green (Crayola)"),
  						new HSVColor("#59260B","Seal brown"),
  						new HSVColor("#FFF5EE","Seashell"),
  						new HSVColor("#FFBA00","Selective yellow"),
  						new HSVColor("#704214","Sepia"),
  						new HSVColor("#8A795D","Shadow"),
  						new HSVColor("#778BA5","Shadow blue"),
  						new HSVColor("#009E60","Shamrock green"),
  						new HSVColor("#8FD400","Sheen green"),
  						new HSVColor("#D98695","Shimmering Blush"),
  						new HSVColor("#5FA778","Shiny Shamrock"),
  						new HSVColor("#FC0FC0","Shocking pink"),
  						new HSVColor("#FF6FFF","Shocking pink (Crayola)"),
  						new HSVColor("#882D17","Sienna"),
  						new HSVColor("#C0C0C0","Silver"),
  						new HSVColor("#C9C0BB","Silver (Crayola)"),
  						new HSVColor("#AAA9AD","Silver (Metallic)"),
  						new HSVColor("#ACACAC","Silver chalice"),
  						new HSVColor("#C4AEAD","Silver pink"),
  						new HSVColor("#BFC1C2","Silver sand"),
  						new HSVColor("#CB410B","Sinopia"),
  						new HSVColor("#FF3855","Sizzling Red"),
  						new HSVColor("#FFDB00","Sizzling Sunrise"),
  						new HSVColor("#007474","Skobeloff"),
  						new HSVColor("#87CEEB","Sky blue"),
  						new HSVColor("#76D7EA","Sky blue (Crayola)"),
  						new HSVColor("#CF71AF","Sky magenta"),
  						new HSVColor("#6A5ACD","Slate blue"),
  						new HSVColor("#708090","Slate gray"),
  						new HSVColor("#299617","Slimy green"),
  						new HSVColor("#C84186","Smitten"),
  						new HSVColor("#100C08","Smoky black"),
  						new HSVColor("#FFFAFA","Snow"),
  						new HSVColor("#893843","Solid pink"),
  						new HSVColor("#757575","Sonic silver"),
  						new HSVColor("#1D2951","Space cadet"),
  						new HSVColor("#807532","Spanish bistre"),
  						new HSVColor("#0070B8","Spanish blue"),
  						new HSVColor("#D10047","Spanish carmine"),
  						new HSVColor("#989898","Spanish gray"),
  						new HSVColor("#009150","Spanish green"),
  						new HSVColor("#E86100","Spanish orange"),
  						new HSVColor("#F7BFBE","Spanish pink"),
  						new HSVColor("#E60026","Spanish red"),
  						new HSVColor("#00FFFF","Spanish sky blue"),
  						new HSVColor("#4C2882","Spanish violet"),
  						new HSVColor("#007F5C","Spanish viridian"),
  						new HSVColor("#A7FC00","Spring bud"),
  						new HSVColor("#87FF2A","Spring Frost"),
  						new HSVColor("#00FF7F","Spring green"),
  						new HSVColor("#ECEBBD","Spring green (Crayola)"),
  						new HSVColor("#007BB8","Star command blue"),
  						new HSVColor("#4682B4","Steel blue"),
  						new HSVColor("#CC33CC","Steel pink"),
  						new HSVColor("#5F8A8B","Steel Teal"),
  						new HSVColor("#FADA5E","Stil de grain yellow"),
  						new HSVColor("#E4D96F","Straw"),
  						new HSVColor("#FA5053","Strawberry"),
  						new HSVColor("#FF9361","Strawberry Blonde"),
  						new HSVColor("#914E75","Sugar Plum"),
  						new HSVColor("#FFCC33","Sunglow"),
  						new HSVColor("#E3AB57","Sunray"),
  						new HSVColor("#FAD6A5","Sunset"),
  						new HSVColor("#CF6BA9","Super pink"),
  						new HSVColor("#A83731","Sweet Brown"),
  						new HSVColor("#D44500","Syracuse Orange"),
  						new HSVColor("#D2B48C","Tan"),
  						new HSVColor("#D99A6C","Tan (Crayola)"),
  						new HSVColor("#F28500","Tangerine"),
  						new HSVColor("#E4717A","Tango pink"),
  						new HSVColor("#FB4D46","Tart Orange"),
  						new HSVColor("#483C32","Taupe"),
  						new HSVColor("#8B8589","Taupe gray"),
  						new HSVColor("#D0F0C0","Tea green"),
  						new HSVColor("#F88379","Tea rose"),
  						new HSVColor("#F4C2C2","Tea rose"),
  						new HSVColor("#008080","Teal"),
  						new HSVColor("#367588","Teal blue"),
  						new HSVColor("#CF3476","Telemagenta"),
	  					new HSVColor("#CD5700","Tenné (tawny)"),
  						new HSVColor("#E2725B","Terra cotta"),
  						new HSVColor("#D8BFD8","Thistle"),
  						new HSVColor("#DE6FA1","Thulian pink"),
  						new HSVColor("#FC89AC","Tickle Me Pink"),
  						new HSVColor("#0ABAB5","Tiffany Blue"),
  						new HSVColor("#DBD7D2","Timberwolf"),
  						new HSVColor("#EEE600","Titanium yellow"),
  						new HSVColor("#FF6347","Tomato"),
  						new HSVColor("#00755E","Tropical rainforest"),
  						new HSVColor("#2D68C4","True Blue"),
  						new HSVColor("#1C05B3","Trypan Blue"),
  						new HSVColor("#3E8EDE","Tufts blue"),
  						new HSVColor("#DEAA88","Tumbleweed"),
  						new HSVColor("#40E0D0","Turquoise"),
  						new HSVColor("#00FFEF","Turquoise blue"),
  						new HSVColor("#A0D6B4","Turquoise green"),
  						new HSVColor("#8A9A5B","Turtle green"),
  						new HSVColor("#FAD6A5","Tuscan"),
  						new HSVColor("#6F4E37","Tuscan brown"),
  						new HSVColor("#7C4848","Tuscan red"),
  						new HSVColor("#A67B5B","Tuscan tan"),
  						new HSVColor("#C09999","Tuscany"),
  						new HSVColor("#8A496B","Twilight lavender"),
  						new HSVColor("#66023C","Tyrian purple"),
  						new HSVColor("#0033AA","UA blue"),
  						new HSVColor("#D9004C","UA red"),
  						new HSVColor("#3F00FF","Ultramarine"),
  						new HSVColor("#4166F5","Ultramarine blue"),
  						new HSVColor("#FF6FFF","Ultra pink"),
  						new HSVColor("#FC6C85","Ultra red"),
  						new HSVColor("#635147","Umber"),
  						new HSVColor("#FFDDCA","Unbleached silk"),
  						new HSVColor("#5B92E5","United Nations blue"),
  						new HSVColor("#A50021","University of Pennsylvania red"),
  						new HSVColor("#FFFF66","Unmellow yellow"),
  						new HSVColor("#014421","UP Forest green"),
  						new HSVColor("#7B1113","UP maroon"),
  						new HSVColor("#AE2029","Upsdell red"),
  						new HSVColor("#AFDBF5","Uranian blue"),
  						new HSVColor("#004F98","USAFA blue"),
  						new HSVColor("#664228","Van Dyke brown"),
  						new HSVColor("#F3E5AB","Vanilla"),
  						new HSVColor("#F38FA9","Vanilla ice"),
  						new HSVColor("#C5B358","Vegas gold"),
  						new HSVColor("#C80815","Venetian red"),
  						new HSVColor("#43B3AE","Verdigris"),
  						new HSVColor("#E34234","Vermilion"),
  						new HSVColor("#D9381E","Vermilion"),
  						new HSVColor("#A020F0","Veronica"),
  						new HSVColor("#8F00FF","Violet"),
  						new HSVColor("#7F00FF","Violet (color wheel)"),
  						new HSVColor("#963D7F","Violet (crayola)"),
  						new HSVColor("#8601AF","Violet (RYB)"),
  						new HSVColor("#EE82EE","Violet (web)"),
  						new HSVColor("#324AB2","Violet-blue"),
  						new HSVColor("#766EC8","Violet-blue (Crayola)"),
  						new HSVColor("#F75394","Violet-red"),
  						new HSVColor("#40826D","Viridian"),
  						new HSVColor("#009698","Viridian green"),
  						new HSVColor("#9F1D35","Vivid burgundy"),
  						new HSVColor("#00CCFF","Vivid sky blue"),
  						new HSVColor("#FFA089","Vivid tangerine"),
  						new HSVColor("#9F00FF","Vivid violet"),
  						new HSVColor("#CEFF00","Volt"),
  						new HSVColor("#004242","Warm black"),
  						new HSVColor("#189BCC","Weezy Blue"),
  						new HSVColor("#F5DEB3","Wheat"),
  						new HSVColor("#FFFFFF","White"),
  						new HSVColor("#A2ADD0","Wild blue yonder"),
  						new HSVColor("#D470A2","Wild orchid"),
  						new HSVColor("#FF43A4","Wild Strawberry"),
  						new HSVColor("#FC6C85","Wild watermelon"),
  						new HSVColor("#A75502","Windsor tan"),
  						new HSVColor("#722F37","Wine"),
  						new HSVColor("#673147","Wine dregs"),
  						new HSVColor("#FF007C","Winter Sky"),
  						new HSVColor("#56887D","Wintergreen Dream"),
  						new HSVColor("#C9A0DC","Wisteria"),
  						new HSVColor("#C19A6B","Wood brown"),
  						new HSVColor("#738678","Xanadu"),
  						new HSVColor("#EEED09","Xanthic"),
  						new HSVColor("#F1B42F","Xanthous"),
  						new HSVColor("#00356B","Yale Blue"),
  						new HSVColor("#FFFF00","Yellow"),
  						new HSVColor("#FCE883","Yellow (Crayola)"),
  						new HSVColor("#EFCC00","Yellow (Munsell)"),
  						new HSVColor("#FFD300","Yellow (NCS)"),
  						new HSVColor("#FEDF00","Yellow (Pantone)"),
  						new HSVColor("#FFEF00","Yellow (process)"),
  						new HSVColor("#FEFE33","Yellow (RYB)"),
  						new HSVColor("#9ACD32","Yellow-green"),
  						new HSVColor("#C5E384","Yellow-green (Crayola)"),
  						new HSVColor("#30B21A","Yellow-green (name Wheel)"),
  						new HSVColor("#FFAE42","Yellow Orange"),
  						new HSVColor("#FF9505","Yellow Orange (name Wheel)"),
  						new HSVColor("#FFF700","Yellow Sunshine"),
  						new HSVColor("#2E5090","YInMn Blue"),
  						new HSVColor("#0014A8","Zaffre"),
  						new HSVColor("#39A78E","Zomp"),
  						new HSVColor("#F95808","Pokemon FireRed"),
  						new HSVColor("#36D959","Pokemon LeafGreen"),
  						new HSVColor("#EDB712","Pokemon Yellow")
					};

			}
		}
	}
}

